# Generated by Django 4.2.5 on 2023-10-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='сервис')),
                ('content', models.TextField(verbose_name='content')),
                ('image', models.ImageField(upload_to='./image/')),
            ],
        ),
    ]
